### ISSUE TITLE
New release of PROPKA

### ISSUE THREAD

**Issue by sobolevnrm** [jensengroup/propka#111]
Hi @speleo3 and @orbeckst --

Based on #105 and other comments, I think we need to release a new bug-fix version of PROPKA.  Do you agree?  if so, I will start the process:

- [ ] @tsenapathi would you be willing to help with the conda release?
- [x] @sobolevnrm Tag and mark release (3.4.0 -- includes some new features/functionality)
- [x] @sobolevnrm Upload to PyPI
- [x] @speleo3 and @orbeckst review #119 
- [x] @sobolevnrm Finish changelog #117 
- [x] Get @orbeckst approval on #113 and merge to master

Thank you,

Nathan

**Comment by speleo3** [comment]
Bug-fix release sounds good to me.

**Comment by tsenapathi** [comment]
@sobolevnrm yes of course I am willing to help with the conda release.

**Comment by sobolevnrm** [comment]
> @sobolevnrm yes of course I am willing to help with the conda release.

Excellent!  3.4.0 has been tagged and pushed to PyP; could you please push to conda?  

Thanks!
